/**
 * Debug Commands - Dev tools for testing
 * Access via browser console with: window.debug.startCombat(), etc.
 */

window.debug = {
    /**
     * Start instant combat with a pirate scout
     */
    startCombat() {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        console.log('[Debug] Starting combat...');
        const enemy = new EnemyShip('pirate_scout', 1);
        window.game.state.combatManager = new CombatManager(window.game.state, enemy);
        window.game.state.combatManager.active = true;
        window.game.state.combatManager.start();
        console.log('[Debug] Combat started with pirate scout!');
    },

    /**
     * Start combat with specific enemy type
     * @param {string} type - 'pirate_scout' or 'pirate_raider'
     * @param {number} threatLevel - 0-5
     */
    startCombatWith(type = 'pirate_scout', threatLevel = 1) {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        console.log(`[Debug] Starting combat with ${type} (threat ${threatLevel})...`);
        const enemy = new EnemyShip(type, threatLevel);
        window.game.state.combatManager = new CombatManager(window.game.state, enemy);
        window.game.state.combatManager.active = true;
        window.game.state.combatManager.start();
        console.log(`[Debug] Combat started!`);
    },

    /**
     * Add credits
     * @param {number} amount - Amount to add
     */
    addCredits(amount = 1000) {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        window.game.state.credits += amount;
        window.game.state.notify();
        console.log(`[Debug] Added ${amount} credits. Total: ${window.game.state.credits}`);
    },

    /**
     * Add scrap
     * @param {number} amount - Amount to add
     */
    addScrap(amount = 50) {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        window.game.state.scrap += amount;
        window.game.state.notify();
        console.log(`[Debug] Added ${amount} scrap. Total: ${window.game.state.scrap}`);
    },

    /**
     * Install module in hardpoint
     * @param {string} hardpoint - 'weapon1', 'weapon2', 'shield', etc.
     * @param {string} moduleId - Module ID from ModuleDefinitions
     */
    installModule(hardpoint, moduleId) {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        // Add to owned modules first if not owned
        if (!window.game.state.ownedModules.includes(moduleId)) {
            window.game.state.ownedModules.push(moduleId);
        }

        const result = window.game.state.installModule(hardpoint, moduleId);
        console.log(`[Debug] Install result:`, result);
    },

    /**
     * Upgrade installed module
     * @param {string} hardpoint - 'weapon1', 'weapon2', 'shield', etc.
     */
    upgradeModule(hardpoint) {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        const result = window.game.state.upgradeModule(hardpoint);
        console.log(`[Debug] Upgrade result:`, result);
    },

    /**
     * List all available modules
     */
    listModules() {
        console.log('Available modules:');
        console.log('WEAPONS:', Object.keys(MODULES).filter(id => MODULES[id].category === 'weapon'));
        console.log('SHIELDS:', Object.keys(MODULES).filter(id => MODULES[id].category === 'shield'));
        console.log('ENGINES:', Object.keys(MODULES).filter(id => MODULES[id].category === 'engine'));
        console.log('JUMP DRIVES:', Object.keys(MODULES).filter(id => MODULES[id].category === 'jump_drive'));
        console.log('REACTORS:', Object.keys(MODULES).filter(id => MODULES[id].category === 'reactor'));
        console.log('BRIDGES:', Object.keys(MODULES).filter(id => MODULES[id].category === 'bridge'));
    },

    /**
     * Heal ship to full
     */
    heal() {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        window.game.state.ship.health = window.game.state.ship.maxHealth;
        window.game.state.ship.shields.currentLayers = window.game.state.ship.shields.maxLayers;
        window.game.state.ship.shields.currentLayerHP = window.game.state.ship.shields.layerHP;
        window.game.state.notify();
        console.log('[Debug] Ship healed to full health and shields');
    },

    /**
     * Start fire at random tile in a room
     * @param {string} roomId - Room ID to pick from LifeSupportManager rooms
     */
    startFire(roomId = 'room_0') {
        if (!window.game || !window.game.state.hazardManager) {
            console.error('[Debug] Game or HazardManager not loaded');
            return;
        }

        // Get all rooms from ship.rooms (generated by ShipLayoutManager)
        const rooms = window.game.state.ship.rooms;
        if (!rooms || rooms.length === 0) {
            console.error('[Debug] No rooms found');
            return;
        }

        // Find room by ID
        const room = rooms.find(r => r.id === roomId);
        if (!room || !room.tiles || room.tiles.length === 0) {
            console.error(`[Debug] Room '${roomId}' not found or has no tiles. Use debug.listRooms() to see available rooms.`);
            return;
        }

        // Pick random tile from room
        const randomTile = room.tiles[Math.floor(Math.random() * room.tiles.length)];
        const x = randomTile[0];
        const y = randomTile[1];

        const success = window.game.state.hazardManager.startFireAt(x, y);
        if (success) {
            console.log(`[Debug] 🔥 Fire started at tile (${x}, ${y}) in room: ${roomId}`);
            console.log(`Fire will spread to adjacent tiles every 5 seconds`);
        } else {
            console.error(`[Debug] Failed to start fire at (${x}, ${y}). Tile may already be burning.`);
        }
    },

    /**
     * Extinguish ALL fires
     */
    extinguishFire() {
        if (!window.game || !window.game.state.hazardManager) {
            console.error('[Debug] Game or HazardManager not loaded');
            return;
        }

        const count = window.game.state.hazardManager.fires.length;
        window.game.state.hazardManager.fires = [];
        console.log(`[Debug] 💧 Extinguished ${count} fires`);
    },

    /**
     * List all rooms with their IDs and status
     */
    listRooms() {
        if (!window.game || !window.game.state.ship.rooms) {
            console.error('[Debug] Game or rooms not loaded');
            return;
        }

        console.log('=== SHIP ROOMS ===');
        window.game.state.ship.rooms.forEach(room => {
            console.log(`Room: ${room.id || 'NO ID'}`);
            console.log(`  - Tiles: ${room.tiles ? room.tiles.length : 0}`);
            console.log(`  - On Fire: ${room.onFire || false}`);
            console.log(`  - Fire Intensity: ${room.fireIntensity || 0}`);
            console.log(`  - Breached: ${room.breached || false}`);
            console.log(`  - Oxygen: ${room.oxygen || 100}`);
        });
    },

    /**
     * Create a breach in a room
     * @param {string} roomId - Room ID
     */
    createBreach(roomId = 'main_hall') {
        if (!window.game || !window.game.state.lifeSupportManager) {
            console.error('[Debug] Game or LifeSupportManager not loaded');
            return;
        }

        const success = window.game.state.lifeSupportManager.createBreach(roomId);
        if (success) {
            console.log(`[Debug] 💥 Breach created in room: ${roomId}`);
        } else {
            console.error(`[Debug] Failed to create breach. Room may not exist or already breached.`);
        }
    },

    /**
     * Create a fire at specified tile coordinates
     * @param {number} x - Tile X coordinate
     * @param {number} y - Tile Y coordinate
     */
    createFire(x, y) {
        if (!window.game) {
            console.error('[Debug] Game not loaded');
            return;
        }

        if (!window.game.state.hazardManager) {
            console.error('[Debug] HazardManager not initialized');
            return;
        }

        window.game.state.hazardManager.createFire(x, y);
        console.log(`[Debug] Fire created at (${x}, ${y})`);
    },

    /**
     * Show help
     */
    help() {
        console.log(`
===== DEBUG COMMANDS =====

Combat:
  debug.startCombat()                    - Start combat with pirate scout (threat 1)
  debug.startCombatWith(type, threat)    - Start combat with specific enemy
                                           Types: 'pirate_scout', 'pirate_raider'
                                           Threat: 0-5

Resources:
  debug.addCredits(1000)                 - Add credits (default 1000)
  debug.addScrap(50)                     - Add scrap (default 50)

Modules:
  debug.listModules()                    - List all available modules
  debug.installModule(slot, moduleId)    - Install module
                                           Slots: 'weapon1', 'weapon2', 'shield', 'engine', etc.
  debug.upgradeModule(slot)              - Upgrade module to next tier

Hazards:
  debug.listRooms()                      - List all rooms and their status
  debug.startFire(roomId)                - Start fire in room (default 'main_hall')
  debug.extinguishFire(roomId)           - Put out fire in room
  debug.createBreach(roomId)             - Create hull breach in room

Other:
  debug.heal()                           - Heal ship to full health & shields
  debug.help()                           - Show this help

Examples:
  debug.startCombat()
  debug.addCredits(5000)
  debug.startFire('cockpit')
  debug.installModule('weapon1', 'railgun')
  debug.upgradeModule('shield')
        `);
    }
};

// Auto-show help on load
console.log('%c🚀 DEBUG COMMANDS LOADED', 'color: #00ff55; font-size: 14px; font-weight: bold;');
console.log('%cType debug.help() for available commands', 'color: #ffaa00;');
